src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Repository\PaymentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaymentRepository::class)
 */
class Payment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Student::class, inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $student;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $method;

    /**
     * @ORM\Column(type="text")
     */
    private $transaction;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;


    /**
     * @ORM\Column(type="text")
     */
    private $payload;

    public function getExpiresAt()
    {
        return $this->date->modify("+" . $this->plan->getPeriod() . " days");
    }


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PaymentPlan")
     */
    private $plan;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getMethod(): ?string
    {
        return $this->method;
    }

    public function setMethod(string $method): self
    {
        $this->method = $method;

        return $this;
    }

    public function getTransaction(): ?string
    {
        return $this->transaction;
    }

    public function setTransaction(string $transaction): self
    {
        $this->transaction = $transaction;

        return $this;
    }

    public function getDate(): \DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function __construct()
    {
        $this->date = new \DateTime();
    }

    /**
     * @return PaymentPlan
     */
    public function getPlan(): ?PaymentPlan
    {
        return $this->plan;
    }

    /**
     * @param PaymentPlan $plan
     * @return Payment
     */
    public function setPlan(PaymentPlan $plan)
    {
        $this->plan = $plan;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * @param mixed $payload
     * @return Payment
     */
    public function setPayload($payload)
    {
        $this->payload = $payload;
        return $this;
    }

}

src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="student", orphanRemoval=true)
     */
    private $payments;

    /**
     * @ORM\ManyToMany(targetEntity=Lesson::class, mappedBy="students")
     */
    private $lessons;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="student", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    public function __construct()
    {
        $this->isActive = false;
        $this->payments = new ArrayCollection();
        $this->lessons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setStudent($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->contains($payment)) {
            $this->payments->removeElement($payment);
            // set the owning side to null (unless already changed)
            if ($payment->getStudent() === $this) {
                $payment->setStudent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
            $lesson->addStudent($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->contains($lesson)) {
            $this->lessons->removeElement($lesson);
            $lesson->removeStudent($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->user ? $this->user->getEmail() : '';
    }

    public function setEmail(string $email): self
    {
        if (!$this->user) {
            $this->user = new User;
        }

        $this->user->setEmail($email);

        return $this;
    }

    public function __toString()
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }


    /**
     * @return mixed
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @param mixed $isActive
     * @return Student
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
        return $this;
    }

}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName', TextType::class, [
                'label' => 'Nombre'
            ])
            ->add('lastName', TextType::class, [
                'label' => 'Apellido'
            ])
            ->add('email', EmailType::class, ['mapped' => false])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'La Contraseña no coincide.',
                'options' => ['attr' => ['class' => 'password-field']],
                'required' => true,
                'first_options' => ['label' => 'Contraseña'],
                'second_options' => ['label' => 'Confirmar Contraseña'],
                'mapped' => false
            ])
            ->add('registrar', SubmitType::class, [
                'label' => 'Registrar Alumno'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/Admin/StudentController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Course;
use App\Entity\Payment;
use App\Entity\PaymentPlan;
use App\Entity\Student;
use App\Entity\Teacher;
use App\Entity\Lesson;
use App\Entity\User;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Router\CrudUrlGenerator;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class StudentController extends AbstractDashboardController
{

    private function getSubscription()
    {

        /** @var Payment[] $payments */
        $payments = $this->getDoctrine()->getRepository(Payment::class)->findBy([
            'student' => $this->getUser()->getStudent()
        ], ["date" => "DESC"]);

        $isSubscribed = false;
        $lastPayment = false;

        if (count($payments) > 0) {
            $lastPayment = $payments[0];

            if ($lastPayment->getDate()->diff(new \DateTime())->days <= $lastPayment->getPlan()->getPeriod()) {
                $isSubscribed = true;
            }
        }

        return [
            'isSubscribed' => $isSubscribed,
            'lastPayment' => $lastPayment
        ];
    }

    /**
     * @Route("/student", name="student")
     */
    public function index(): Response
    {
        $routeBuilder = $this->get(CrudUrlGenerator::class)->build();
        $subscription = $this->getSubscription();

        if ($subscription['isSubscribed']) {
            return $this->redirect($routeBuilder->setController(LessonCrudController::class)->generateUrl());
        } else {
            return $this->redirectToRoute('student_subscription');
        }
    }

    /**
     * @Route("/student/subscription", name="student_subscription")
     */
    public function subscription(): Response
    {
        $plans = $this->getDoctrine()->getRepository(PaymentPlan::class)->findBy([
            'isActive' => true,
        ]);

        $subscription = $this->getSubscription();

        return $this->render("student/subscription.html.twig", [
//            'payments' => $payments,
            'plans' => $plans,
            'isSubscribed' => $subscription['isSubscribed'],
            'lastPayment' => $subscription['lastPayment'],
        ]);
    }

    /**
     * @Route("/student/subscription/{id}/buy", name="student_subscription_buy")
     */
    public function subscriptionBuy(PaymentPlan $paymentPlan): Response
    {
        return $this->render('student/subscriptionBuy.html.twig', [
            'plan' => $paymentPlan,
        ]);

    }

    /**
     * @Route("/student/verify", name="verify_payment")
     */
    public function verifyPayment(Request $request): Response
    {


        $paypalObj = json_decode($request->getContent());
        if ($paypalObj->status == "COMPLETED") {
            $em = $this->getDoctrine()->getManager();

            $plan = $this->getDoctrine()->getRepository(PaymentPlan::class)->find($request->get("id"));

            $payment = new Payment();
            $payment->setPlan($em->getReference(PaymentPlan::class, $plan->getId()));
            $payment->setTransaction($paypalObj->id);
            $payment->setPayload($request->getContent());
            $payment->setStudent($this->getUser()->getStudent());
            $payment->setAmount($plan->getAmount());
            $payment->setMethod("PayPal");

            $em->persist($payment);
            $em->flush();

            return new JsonResponse([
                'status' => 'SUCCESS',
            ]);
        }
        return new JsonResponse([
            'status' => 'FAILED',
        ]);


        dd($paypalObj);
    }


    /**
     * @Route("/student/subscription/buy2", name="student_subscription_buy2")
     */
    public function subscriptionBuy2(Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();

        $payment = new Payment();
        $payment->setStudent($this->getUser()->getStudent());
        $payment->setMethod('test');
        $payment->setAmount(123);
        $payment->setTransaction(1);
        $payment->setPlan($em->getReference(PaymentPlan::class, $request->get('id')));

        $em->persist($payment);
        $em->flush();

        return $this->redirectToRoute('student_subscription');
    }


    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('Wesdap');
    }

    public function configureMenuItems(): iterable
    {

        $lastPayment = $this->getDoctrine()->getRepository('App:Payment')->findLastPayment($this->getUser()->getStudent());
        $isSubscribed = false;

        if ($lastPayment != null && $lastPayment->getDate()->diff(new \DateTime())->days <= $lastPayment->getPlan()->getPeriod()) {
            $isSubscribed = true;
        }

        if ($isSubscribed) {
            yield MenuItem::section('Programas');
            yield MenuItem::linkToCrud('Programas', 'fa fa-users', Course::class);

            yield MenuItem::section('Aulas');
            yield MenuItem::linkToCrud('Aulas', 'fa fa-users', Lesson::class);
        }

        yield MenuItem::section('Perfil');
        yield MenuItem::linktoRoute('Subscription', 'fa fa-money', "student_subscription");
        if ($this->getUser()->getStudent() != null) {
            yield MenuItem::linkToCrud('Perfil', 'fa fa-users', Student::class)
                ->setAction('edit')
                ->setEntityId($this->getUser()->getStudent()->getId());
        }

        yield MenuItem::linkToCrud('Acceso', 'fa fa-users', User::class)
            ->setAction('edit')
            ->setEntityId($this->getUser()->getId());
    }
}

templates/student/list.html.twig
{% extends '@EasyAdmin/layout.html.twig' %}

{% block content_header_wrapper %} {% endblock content_header_wrapper %}



{% block main %}


{% endblock main %}


{% block content_footer_wrapper %} {% endblock content_footer_wrapper %}

templates/student/subscription.html.twig
{% extends '@EasyAdmin/layout.html.twig' %}

{% block content_header_wrapper %} {% endblock content_header_wrapper %}



{% block main %}

    {% if isSubscribed %}
        <div>
            Your current subscription plan: {{ lastPayment.plan.title }}
        </div>
        <div>
            Expires at: {{ lastPayment.expiresAt | date("Y-m-d H:i") }}
        </div>
    {% else %}
        {% for __plan in plans %}
            <a href="{{ path("student_subscription_buy", {'id':__plan.id}) }}" class="btn btn-success">
                {{ 'Buy subscription' }} {{ __plan.title }}
            </a>
        {% endfor %}
    {% endif %}


{% endblock main %}


{% block content_footer_wrapper %} {% endblock content_footer_wrapper %}

templates/student/subscriptionBuy.html.twig
{% extends '@EasyAdmin/layout.html.twig' %}

{% block content_header_wrapper %} {% endblock content_header_wrapper %}



{% block main %}
    <script src="https://www.paypal.com/sdk/js?client-id=AQmeXc_sCuNVKmDEF_mKobRhY1-f368oKG0q2HkSdazBBO3FHJArfK4_df9NDRH4nCyGo7Y7m9tqtZCv"></script>

    <div style="font-size: 18px; font-weight: bold">
        PAYPAL DEMO<br>
        email: sb-q47noi4704629@personal.example.com<br>
        pass: 123123123<br>

    </div>

    <div style="display: flex; font-size: 24px;">
        <div style="flex: 1; padding: 30px">
            <table>
                <tr>
                    <td colspan="2">{{ "Your subscription plan" | trans }}</td>
                </tr>
                <tr>
                    <td>{{ "Period" }}</td>
                    <td>{{ plan.period }} {{ "days" | trans }}</td>
                </tr>
                <tr>
                    <td>{{ "Price" }}</td>
                    <td>{{ plan.amount }} {{ "$" | trans }}</td>
                </tr>
            </table>
        </div>
        <div style="flex: 1; padding: 30px">
            <div id="paypal-buttons"></div>
            <script src="https://www.paypal.com/sdk/js?client-id=sb"></script>
            <script>paypal.Buttons({
                    createOrder: function (data, actions) {
                        return actions.order.create({
                            purchase_units: [{
                                amount: {
                                    value: {{ plan.amount }}
                                }
                            }]
                        });
                    },
                    onApprove: function (data, actions) {
                        // This function captures the funds from the transaction.

                        return actions.order.capture().then(function (details) {
                            fetch("{{ path("verify_payment", {id:plan.id}) }}", {
                                method: 'POST',
                                mode: 'cors',
                                cache: 'no-cache',
                                credentials: 'same-origin',
                                headers: {
                                    'Content-Type': 'application/json'
                                },
                                redirect: 'follow',
                                referrerPolicy: 'no-referrer',
                                body: JSON.stringify(details)
                            })
                                .then((data) => {
                                    return data.json();
                                })
                                .then((response) => {
                                    if (response.status == "SUCCESS") {
                                        location.href = "{{ path("student") }}";
                                    } else {
                                        alert("PAYMENT ERROR");
                                    }
                                });
                        });
                    }
                }).render('#paypal-buttons');</script>
        </div>
    </div>
{% endblock main %}


{% block content_footer_wrapper %} {% endblock content_footer_wrapper %}